### PR TITLE
Developer Guide Creation

### LINKED ISSUE #74: Add Git Resource information to GCAM Developer's Guide
Add a section on git resources to the GCAM developer's guide (https://github.com/JGCRI/gcam-doc/blob/developer-guide/dev-guide/git.md). Possible topics to include: best practices, branch naming rules, links to other resources, github vs stash.

Information on this page may be useful: https://confluence.pnnl.gov/confluence/display/JGCRI/Git+Resources

### LINKED ISSUE #75: Add style guide to GCAM developer's guide
Add a section on GCAM style to the GCAM developer's guide (https://github.com/JGCRI/gcam-doc/blob/developer-guide/dev-guide/style.md).

### LINKED ISSUE #76: Add getting started to GCAM developer's guide
Write the "getting started" section of the GCAM developer's guide (https://github.com/JGCRI/gcam-doc/blob/developer-guide/dev-guide/getting_started.md).

Some relevant information is available at: https://confluence.pnnl.gov/confluence/display/JGCRI/GCAM+Development+Guide

### LINKED ISSUE #77: Add section on review process to GCAM developer's guide
Add review process section to developer's guide (https://github.com/JGCRI/gcam-doc/blob/developer-guide/dev-guide/review.md).

See https://confluence.pnnl.gov/confluence/display/JGCRI/GCAM+Core+Model+Proposals for information

### LINKED ISSUE #78: Add additional information to developer's guide
Write the section on additional resources in the developer's guide (https://github.com/JGCRI/gcam-doc/blob/developer-guide/dev-guide/additional_info.md).

This could potentially include: links to tutorials and guidance on communication.

### LINKED ISSUE #79: Add a section on analysis tools to GCAM developer's guide
Write a section on analysis tools (e.g., rgcam) for the GCAM developer's guide (https://github.com/JGCRI/gcam-doc/blob/developer-guide/dev-guide/analysis.md).

### LINKED ISSUE #80: Add FAQ section to GCAM developer's guide
Write the FAQ / common issue section of the GCAM developer's guide (https://github.com/JGCRI/gcam-doc/blob/developer-guide/dev-guide/faq.md).

Potential issues to include: regenerating sysdata.rda.
Potentially relevant information: https://confluence.pnnl.gov/confluence/display/JGCRI/Debug+GCAM+executable, 
https://confluence.pnnl.gov/confluence/display/JGCRI/Setting+up+GCAM+on+PIC
https://confluence.pnnl.gov/confluence/pages/viewpage.action?pageId=122720966
https://confluence.pnnl.gov/confluence/display/JGCRI/Debug+Solution+Issues

### LINKED ISSUE #81: Reorganize GCAM fusion information
Move developer-related fusion information to the examples section of the GCAM developer guide (https://github.com/JGCRI/gcam-doc/blob/developer-guide/dev-guide/examples.md).

### LINKED ISSUE #82: Add information on the GCAM ecosystem in the GCAM developer guide
Add links and relevant information on the GCAM ecosystem as appropriate throughout the GCAM developer's guide (https://github.com/JGCRI/gcam-doc/blob/developer-guide/dev_guide.md)

### LINKED ISSUE #83: Add gcamdata information belongs in GCAM developer's guide
Determine what gcamdata information belongs in GCAM developer's guide and add it to the appropriate sections. This could include a style guide or links to any existing resources.

### PR DESCRIPTION
**Pull request by crvernon**
STATUS:  *Complete*

This PR will address several development guide issues assigned to multiple collaborators.  Each issue is focused on adding content to each preset section of the development guide.  The sections, assignments, resulting issues, and status are represented in the following:

| Section | Assignee | Issue | Status |
| ------- | ------- | ------- | ------- |
| Git resource information | @rplzzz | Resolves #74 | ready for review |
| Style guide | @skim301 | Resolves #75 | ready for review |
| Getting started | @kvcalvin | Resolves #76 | ready for review |
| Review process | @kvcalvin | Resolves #77 | ready for review |
| Additional information | @kvcalvin | Resolves #78 | ready for review |
| Analysis tools | @crvernon | Resolves #79 | ready for review |
| FAQ | @pralitp | Resolves #80 | ready for review |
| GCAM Fusion reorganization | @pralitp | Resolves #81 | ready for review |
| GCAM Ecosystem | @crvernon | Resolves #82 | ready for review |
| `gcamdata` information updates | @bpbond | Resolves #83 | ready for review |

Please update individual section status on change and review.

### CODE REVIEW

**Comment by crvernon** [comment]
@kvcalvin I decided to merge the needs in issues #79 and #82 to provide a summary of GCAM ecosystem models and tools related to GCAM.  These are broken out categorically.  I provided a description of each model or tool and a link to their code repository.  Let me know if you think it would be good to provide model development paper references for those that may have them.  I also changed to page title from `GCAM Analysis Tools` to `GCAM Ecosystem of Models and Tools`.  

Here is the page reference containing my additions:  https://github.com/JGCRI/gcam-doc/blob/developer-guide/dev-guide/analysis.md

**Comment by kvcalvin** [comment]
Sounds good

**Comment by kvcalvin** [comment]
@mwisepnnl: This is now complete and ready for review.

**Review by mwisepnnl — APPROVED** [review]
I didn't see anything wrong. I believe I read every line.   I'm sure there could be more in some areas, but we can worry about that in the future.  So I say we should go ahead.

**Pull request merged**
