### PR TITLE
Base x instructions

### PR DESCRIPTION
**Pull request by ssmithClimate**
Add section describing updating BaseX database.

### CODE REVIEW

**Comment by ssmithClimate** [comment]
Wrong base. closing

**Comment by ssmithClimate** [comment]
Here's the modified file:
[gcam-build.md](https://github.com/JGCRI/gcam-doc/files/6359104/gcam-build.md)

**Comment by kvcalvin** [comment]
@ssmithClimate and @pralitp : Is this still needed or is it incorporated in the former `next` branch which was merged with `doc-reorg`?

**Comment by ssmithClimate** [comment]
@kvcalvin I suspect its still required, I don't believe this got into the public version at least. 

The part that was new is this sub-section:

#### 2.3.6 BaseX
BaseX is an XML database used for writing out 
comprehensive GCAM model 
output. Most users will be set-up for using BaseX by copying libraries
and model interface files from a distribution version of GCAM as 
discussed above. If for some reason you are downloading 
BaseX directly from the [BaseX web site](https://basex.org/download/)
note that the BaseX.jar library must be renamed 
exactly as `BaseX-9.5.0.jar`.

**Comment by ssmithClimate** [comment]
But its possible that @pralitp changed something such that this is no longer necessary.

**Comment by kvcalvin** [comment]
I've added what @ssmithClimate suggested to `doc-reorg`. Closing this one.

**Pull request closed without merging**
