### PR TITLE
Add chapters for energy system documentation

### PR DESCRIPTION
**Pull request by pkyle**
Includes the following 8 energy system components: renewables, transformation, refining, gas processing, hydrogen, district heat, technologies in general, and mapping the IEA energy balances.

### CODE REVIEW

**Comment by rplzzz** [comment]
Is there any work still happening on this branch?  I thought Leon told me that someone was consolidating these additions into a single chapter, but I don't know who's doing it or what their time table is.

**Comment by pkyle** [comment]
Well if it was anyone's job to consolidate what I put together, it wasn't me! And that likely wouldn't happen until all pages are done. I'm done with all of mine (though nobody has reviewed them), but I don't think the others have started work on theirs.

**Comment by rplzzz** [comment]
I think it was supposed to be one of the students or post-*s.  I'll ask Leon about it.  I'll give it a read-through once that's done, and I'll ask @bpbond to do the same.

**Comment by pralitp** [comment]
These changes were incorporated in PR 11 instead where they had all been collapsed into a single energy.md file.

**Comment by rplzzz** [comment]
Is this branch obsolete then?  If so, we can delete it.

**Pull request closed without merging**
